from __future__ import annotations
import argparse,json,re,sys
from pathlib import Path
from .porter import port_map
from .assembler import analyze_and_assemble
from .assets.gfxworld import GfxWorldResourcePolicy
from .assets.image import ImageResourcePolicy
from .ps3_budget import DEFAULT_MIN_BASE_DIMENSION,DEFAULT_ZONE_BUDGET_BYTES,RETAIL_PS3_MAX_TEXTURE_EDGE,RETAIL_PS3_SHIPMENT_ZONE_BYTES

MAP_NAME_RE=re.compile(r'^mp_[a-z0-9_]+$')


def _read_json(path):
    return {} if not path else json.loads(Path(path).read_text(encoding='utf-8-sig'))

def main(argv=None):
    ap=argparse.ArgumentParser(prog='cod4porter-python',description='COD4 IW3 PC -> PS3 FastFile porter (independent Python production path)')
    sub=ap.add_subparsers(dest='cmd',required=True)
    a=sub.add_parser('analyze');a.add_argument('--pc-ff',required=True);a.add_argument('--map',required=True);a.add_argument('--iwd',action='append',default=[]);a.add_argument('--ffmpeg',default='ffmpeg');a.add_argument('--runtime-compatible',action='store_true')
    a.add_argument('--owner-aware-visual-graph',action='store_true',help='compatibility alias: the complete Material/Image owner graph is now the default')
    a.add_argument('--boot-isolation',action='store_true',help='explicit diagnostic mode: replace the live visual graph with shared-default roots')
    a.add_argument('--gfxworld-resource-policy',choices=[x.value for x in GfxWorldResourcePolicy],default=GfxWorldResourcePolicy.FASTFILE_DELAYED.value,help='fastfile-delayed writes the complete PS3 image FIFO into block 3; retail-delayed is metadata-only; self-contained embeds diagnostic B6 resources')
    a.add_argument('--material-image-resource-policy',choices=[x.value for x in ImageResourcePolicy],default=ImageResourcePolicy.FASTFILE_DELAYED.value,help='fastfile-delayed uses block 3; self-contained uses block 6; balanced-split preserves every image while distributing complete payloads across both; retail-delayed omits payloads')
    a.add_argument('--sound-policy',choices=('omit','map-owned'),default='omit',help='omit writes no map-specific Sound/SndCurve/LoadedSound assets (default)')
    p=sub.add_parser('port');p.add_argument('--pc-ff',required=True);p.add_argument('--map',required=True);p.add_argument('--iwd',action='append',default=[]);p.add_argument('--out',required=True);p.add_argument('--load-baseline',help='legacy: rebuild an already matching PS3 load zone');p.add_argument('--pc-load-ff',help='PC *_load.ff to convert into a fresh PS3 load zone');p.add_argument('--ps3-load-reference',help='optional audited PS3 load zone supplying the exact stock victory-screen pixels');p.add_argument('--ffmpeg',default='ffmpeg');p.add_argument('--cubemap-evidence',help='JSON map of normalized source cubemap name to six independently observed PS3-retail face hashes');p.add_argument('--allow-unproven-retail',action='store_true',help='return success after structural conversion even when retail-only fidelity evidence is missing; never changes generated bytes');p.add_argument('--runtime-compatible',action='store_true',help='permit explicitly reported loader-safe compatibility fallbacks for unresolved source semantics; changes generated bytes and cannot Full-Fidelity pass')
    p.add_argument('--owner-aware-visual-graph',action='store_true',help='compatibility alias: the complete Material/Image owner graph is now the default')
    p.add_argument('--boot-isolation',action='store_true',help='explicit diagnostic mode: replace the live visual graph with shared-default roots')
    p.add_argument('--gfxworld-resource-policy',choices=[x.value for x in GfxWorldResourcePolicy],default=GfxWorldResourcePolicy.FASTFILE_DELAYED.value,help='select exactly one GfxWorld image-resource policy; fastfile-delayed is the complete PS3 runtime output')
    p.add_argument('--material-image-resource-policy',choices=[x.value for x in ImageResourcePolicy],default=ImageResourcePolicy.FASTFILE_DELAYED.value,help='fastfile-delayed uses block 3; self-contained uses block 6; balanced-split preserves every image while distributing complete payloads across both; retail-delayed omits payloads')
    p.add_argument('--sound-policy',choices=('omit','map-owned'),default='omit',help='omit writes no map-specific Sound/SndCurve/LoadedSound assets (default)')
    p.add_argument('--unresolved-image-policy',choices=('reference','neutral'),default='reference',help="what to write for an image the PC sources do not supply: 'reference' emits a ,name the console must resolve, which no Retail PS3 map ever does; "
        "'neutral' writes a tiny owned placeholder instead, so the zone carries no dangling image reference")
    p.add_argument('--unresolved-material-policy',choices=('reference','default'),default='reference',help="what to write for a shared Material no loaded PS3 zone owns: 'reference' keeps the ,name; 'default' rebinds it to ,default, which every always-loaded zone carries")
    p.add_argument('--primary-light-policy',choices=('source','sun-only'),default='source',help="'source' keeps every PC primary light; 'sun-only' keeps the sun and collapses the rest onto it - Retail PS3 maps ship 2-5 primary lights, a ported PC map can declare a hundred")
    p.add_argument('--gfxworld-vertex-layers',choices=('source','omit'),default='source',help="diagnostic: 'omit' declares zero GfxWorld vertex-layer bytes and zeroes every surface layer offset")
    p.add_argument('--gfxworld-portals',choices=('source','omit'),default='source',help='diagnostic: GfxWorld portals are not converted yet; \'omit\' writes every cell with portalCount 0 so a multi-cell map can still be built')
    p.add_argument('--ps3-zone-budget',default=str(DEFAULT_ZONE_BUDGET_BYTES),help=f'maximum declared zone allocation in bytes, or "off" to disable the gate; the default {DEFAULT_ZONE_BUDGET_BYTES} is the measured Retail PS3 mp_shipment zone ({RETAIL_PS3_SHIPMENT_ZONE_BYTES} bytes). Oversized textures are reduced by whole mip levels until the map fits')
    p.add_argument('--image-budget-min-dimension',type=int,default=DEFAULT_MIN_BASE_DIMENSION,help='never shrink a texture below this base edge length while meeting the zone budget')
    p.add_argument('--texture-max-edge',type=int,default=RETAIL_PS3_MAX_TEXTURE_EDGE,help=f'cap every texture at this base edge length, matching the Retail PS3 convention (default {RETAIL_PS3_MAX_TEXTURE_EDGE}; Retail ships the bulk at 256). Use 0 to keep PC resolution and rely on the zone budget alone')
    for parser in (a,p):parser.add_argument('--unsupported-fx',choices=('omit','error'),default='omit',help='omit unsupported FX and exclusive dependencies; error keeps strict behavior')
    for parser in (a,p):parser.add_argument('--shader-compilation',choices=('auto','prefer','off'),default='auto',help='auto: compile PC shaders to RSX for TechniqueSets without a native PS3 identity; prefer: also replace family substitutions with faithful compiled graphs; off: name binding only')
    for parser in (a,p):parser.add_argument('--donor-catalog',default=None,help='techset-donors.json exported by the Emulator "techsets" command; matching TechniqueSets are transplanted byte-faithfully from retail PS3 data')
    ns=ap.parse_args(argv)
    try:
      if not MAP_NAME_RE.fullmatch(ns.map):
        raise ValueError('--map must match ^mp_[a-z0-9_]+$ (lower-case multiplayer map name)')
      if ns.boot_isolation and ns.owner_aware_visual_graph:
        raise ValueError('--boot-isolation and --owner-aware-visual-graph are mutually exclusive')
      boot_isolation=bool(ns.boot_isolation)
      if ns.cmd=='analyze':
        r=analyze_and_assemble(ns.pc_ff,ns.map,ns.iwd,ffmpeg=ns.ffmpeg,runtime_compatible=ns.runtime_compatible,boot_isolation=boot_isolation,gfxworld_resource_policy=ns.gfxworld_resource_policy,material_image_resource_policy=ns.material_image_resource_policy,sound_policy=ns.sound_policy,unsupported_fx_policy=ns.unsupported_fx,shader_compilation=ns.shader_compilation,donor_catalog=ns.donor_catalog);print(json.dumps({'passed':True,'source':dict(r.source.diagnostics),'assembly':dict(r.diagnostics)},indent=2,default=str));return 0
      cube=_read_json(ns.cubemap_evidence)
      budget=str(ns.ps3_zone_budget).strip().lower()
      if budget in ('off','none','0'):
        zone_budget=None
      else:
        zone_budget=int(budget,0)
        if zone_budget<=0:
          raise ValueError('--ps3-zone-budget must be a positive byte count or "off"')
      if ns.image_budget_min_dimension<1:
        raise ValueError('--image-budget-min-dimension must be at least 1')
      r=port_map(ns.pc_ff,ns.map,ns.iwd,ns.out,load_baseline=ns.load_baseline,pc_load_ff=ns.pc_load_ff,retail_load_reference=ns.ps3_load_reference,ffmpeg=ns.ffmpeg,cubemap_target_face_hashes=cube,runtime_compatible=ns.runtime_compatible,boot_isolation=boot_isolation,gfxworld_resource_policy=ns.gfxworld_resource_policy,material_image_resource_policy=ns.material_image_resource_policy,sound_policy=ns.sound_policy,unsupported_fx_policy=ns.unsupported_fx,shader_compilation=ns.shader_compilation,donor_catalog=ns.donor_catalog,unresolved_image_policy=ns.unresolved_image_policy,unresolved_material_policy=ns.unresolved_material_policy,primary_light_policy=ns.primary_light_policy,vertex_layer_policy=ns.gfxworld_vertex_layers,portal_policy=ns.gfxworld_portals,zone_budget_bytes=zone_budget,image_budget_min_dimension=ns.image_budget_min_dimension,texture_max_edge=ns.texture_max_edge)
      print(json.dumps(r,indent=2,default=str))
      if not r.get('full_fidelity_passed') and not ns.allow_unproven_retail:return 2
      return 0
    except Exception as e:
      print(json.dumps({'passed':False,'error':str(e)},indent=2),file=sys.stderr);return 2

if __name__=='__main__':raise SystemExit(main())
