<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>13.0</LangVersion>
    <Deterministic>true</Deterministic>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
    <Company>IW3MapPorter</Company>
    <Product>IW3MapPorter Desktop</Product>
  </PropertyGroup>
</Project>
